// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqgfdkspanrehcssmjpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZ2Zka3NwYW5yZWhjc3NtanB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDYyMTYsImV4cCI6MjA3MzA4MjIxNn0.ZUzOfadbdT5EKPNfR02F0amxkG8IgOScCx57qPVAcI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});